// Generated by https://quicktype.io
import { BaseModel } from './base.model';
import { UserInfoModel } from './user-info.model';

export interface AccountModel extends BaseModel, UserInfoModel {
    createdByUserId: string;
    updatedByUserId: string;
    passwordText: string;
    salt: string;
    token: string;
    lastJwt: string;
    roles: string[];
    typeLogin: string;
    avatar: string;
}
